import type { Place, PlaceCategory } from "../types";

export const STORAGE_KEY = "tripyojana_map_data";
export const DATA_VERSION = "v2_india_temples";

export const INITIAL_PLACES: Place[] = [
  {
    id: "1",
    name: "Golden Temple",
    description: "Harmandir Sahib - Most sacred Sikh shrine",
    lat: 31.6200,
    lng: 74.8765,
    category: "attraction",
    time: "6:00 AM",
    address: "Golden Temple Road, Amritsar, Punjab, India",
  },
  {
    id: "2",
    name: "Meenakshi Temple",
    description: "Historic Hindu temple with stunning architecture",
    lat: 9.9195,
    lng: 78.1193,
    category: "attraction",
    time: "8:00 AM",
    address: "Madurai Main, Madurai, Tamil Nadu, India",
  },
  {
    id: "3",
    name: "Tirupati Balaji Temple",
    description: "Lord Venkateswara Temple - World's richest temple",
    lat: 13.6833,
    lng: 79.3472,
    category: "attraction",
    time: "5:00 AM",
    address: "Tirumala, Tirupati, Andhra Pradesh, India",
  },
  {
    id: "4",
    name: "Konark Sun Temple",
    description: "UNESCO World Heritage Site - 13th century Sun Temple",
    lat: 19.8876,
    lng: 86.0945,
    category: "attraction",
    time: "10:00 AM",
    address: "Konark, Puri, Odisha, India",
  },
  {
    id: "5",
    name: "Somnath Temple",
    description: "First among twelve Jyotirlinga shrines of Shiva",
    lat: 20.8880,
    lng: 70.4013,
    category: "attraction",
    time: "7:00 AM",
    address: "Veraval, Somnath, Gujarat, India",
  },
  {
    id: "6",
    name: "Vaishno Devi Temple",
    description: "Holy cave temple dedicated to Goddess Vaishno Devi",
    lat: 33.0308,
    lng: 74.9495,
    category: "attraction",
    time: "4:00 AM",
    address: "Katra, Reasi, Jammu & Kashmir, India",
  },
  {
    id: "7",
    name: "Kedarnath Temple",
    description: "Sacred Shiva temple in the Himalayas - Char Dham pilgrimage",
    lat: 30.7346,
    lng: 79.0669,
    category: "attraction",
    time: "6:00 AM",
    address: "Kedarnath, Rudraprayag, Uttarakhand, India",
  },
  {
    id: "8",
    name: "Kashi Vishwanath Temple",
    description: "One of the most famous Hindu temples dedicated to Lord Shiva",
    lat: 25.3109,
    lng: 83.0107,
    category: "attraction",
    time: "5:00 AM",
    address: "Varanasi, Uttar Pradesh, India",
  },
  {
    id: "9",
    name: "Mahakaleshwar Temple",
    description: "One of the twelve Jyotirlingas - Ancient Shiva temple",
    lat: 23.1765,
    lng: 75.7685,
    category: "attraction",
    time: "6:00 AM",
    address: "Ujjain, Madhya Pradesh, India",
  },
  {
    id: "10",
    name: "Hidimba Devi Temple",
    description: "Ancient cave temple surrounded by cedar forests in Manali",
    lat: 32.2396,
    lng: 77.1887,
    category: "attraction",
    time: "8:00 AM",
    address: "Manali, Himachal Pradesh, India",
  },
  {
    id: "11",
    name: "Abbey Falls",
    description: "Beautiful waterfall in coffee plantations of Coorg",
    lat: 12.4539,
    lng: 75.7200,
    category: "activity",
    time: "10:00 AM",
    address: "Coorg (Kodagu), Karnataka, India",
  },
  {
    id: "12",
    name: "Triveni Ghat",
    description: "Sacred bathing ghat on the Ganges - Yoga capital of the world",
    lat: 30.0869,
    lng: 78.2676,
    category: "attraction",
    time: "6:00 AM",
    address: "Rishikesh, Uttarakhand, India",
  },
  {
    id: "13",
    name: "Virupaksha Temple",
    description: "UNESCO World Heritage Site - Ancient temple complex in Hampi",
    lat: 15.3350,
    lng: 76.4620,
    category: "attraction",
    time: "9:00 AM",
    address: "Hampi, Karnataka, India",
  },
];

export const CATEGORY_COLORS: Record<PlaceCategory, string> = {
  attraction: "#3b82f6",
  restaurant: "#ef4444",
  hotel: "#8b5cf6",
  activity: "#10b981",
};

export const CATEGORY_ICONS: Record<PlaceCategory, string> = {
  attraction: "🏛️",
  restaurant: "🍽️",
  hotel: "🏨",
  activity: "🎯",
};

// Map configuration
export const MAP_DEFAULTS = {
  WORLD_CENTER: [20, 0] as [number, number],
  INDIA_CENTER: [22.5, 78.9] as [number, number],
  INDIA_BOUNDS: {
    minLat: 6,
    maxLat: 37,
    minLng: 68,
    maxLng: 97,
  },
  DEFAULT_ZOOM: 2,
  PLACES_ZOOM: 4,
  MAP_PADDING: [50, 50] as [number, number],
};
