import { ReactNode } from "react";

export interface CategoryBudget {
  id: string;
  name: string;
  allocated: number;
  spent: number;
  color: string;
  icon?: ReactNode;
}

export const TRIP_BUDGETS: Record<string, { totalBudget: number; tripName: string; dates: string; categories: CategoryBudget[] }> = {
  "1": {
    totalBudget: 25000,
    tripName: "Golden Temple Trip",
    dates: "April 2026",
    categories: [
      {
        id: "travel",
        name: "Travel & Transport",
        allocated: 9000,
        spent: 5500,
        color: "bg-blue-500",
        icon: null,
      },
      {
        id: "hotel",
        name: "Accommodation",
        allocated: 8000,
        spent: 6000,
        color: "bg-purple-500",
        icon: null,
      },
      {
        id: "food",
        name: "Food & Dining",
        allocated: 5000,
        spent: 2800,
        color: "bg-green-500",
        icon: null,
      },
      {
        id: "activities",
        name: "Activities & Shopping",
        allocated: 3000,
        spent: 2100,
        color: "bg-orange-500",
        icon: null,
      },
    ],
  },
  "2": {
    totalBudget: 35000,
    tripName: "Tirupati Trip",
    dates: "June 2026",
    categories: [
      {
        id: "travel",
        name: "Travel & Transport",
        allocated: 11000,
        spent: 8500,
        color: "bg-blue-500",
        icon: null,
      },
      {
        id: "hotel",
        name: "Accommodation",
        allocated: 12000,
        spent: 10000,
        color: "bg-purple-500",
        icon: null,
      },
      {
        id: "food",
        name: "Food & Dining",
        allocated: 7000,
        spent: 4200,
        color: "bg-green-500",
        icon: null,
      },
      {
        id: "activities",
        name: "Temple & Activities",
        allocated: 5000,
        spent: 3800,
        color: "bg-orange-500",
        icon: null,
      },
    ],
  },
  "3": {
    totalBudget: 30000,
    tripName: "Vaishno Devi Trip",
    dates: "August 2026",
    categories: [
      {
        id: "travel",
        name: "Travel & Transport",
        allocated: 12000,
        spent: 9500,
        color: "bg-blue-500",
        icon: null,
      },
      {
        id: "hotel",
        name: "Accommodation",
        allocated: 10000,
        spent: 8000,
        color: "bg-purple-500",
        icon: null,
      },
      {
        id: "food",
        name: "Food & Trek Supplies",
        allocated: 5000,
        spent: 2800,
        color: "bg-green-500",
        icon: null,
      },
      {
        id: "activities",
        name: "Trek & Activities",
        allocated: 3000,
        spent: 2200,
        color: "bg-orange-500",
        icon: null,
      },
    ],
  },
  "4": {
    totalBudget: 45000,
    tripName: "Kedarnath Trip",
    dates: "May 2026",
    categories: [
      {
        id: "travel",
        name: "Travel & Transport",
        allocated: 17000,
        spent: 14000,
        color: "bg-blue-500",
        icon: null,
      },
      {
        id: "hotel",
        name: "Accommodation",
        allocated: 15000,
        spent: 12500,
        color: "bg-purple-500",
        icon: null,
      },
      {
        id: "food",
        name: "Food & Supplies",
        allocated: 8000,
        spent: 5600,
        color: "bg-green-500",
        icon: null,
      },
      {
        id: "activities",
        name: "Trek & Adventures",
        allocated: 5000,
        spent: 4200,
        color: "bg-orange-500",
        icon: null,
      },
    ],
  },
  "5": {
    totalBudget: 32000,
    tripName: "Mahakaleshwar Temple, Ujjain Trip",
    dates: "July 2026",
    categories: [
      {
        id: "travel",
        name: "Travel & Transport",
        allocated: 12000,
        spent: 9000,
        color: "bg-blue-500",
        icon: null,
      },
      {
        id: "hotel",
        name: "Accommodation",
        allocated: 10000,
        spent: 7000,
        color: "bg-purple-500",
        icon: null,
      },
      {
        id: "food",
        name: "Food & Dining",
        allocated: 6000,
        spent: 3600,
        color: "bg-green-500",
        icon: null,
      },
      {
        id: "activities",
        name: "Aarti & Sightseeing",
        allocated: 4000,
        spent: 2450,
        color: "bg-orange-500",
        icon: null,
      },
    ],
  },
  "6": {
    totalBudget: 28000,
    tripName: "Jagannath Temple, Puri Trip",
    dates: "September 2026",
    categories: [
      {
        id: "travel",
        name: "Travel & Transport",
        allocated: 10000,
        spent: 8500,
        color: "bg-blue-500",
        icon: null,
      },
      {
        id: "hotel",
        name: "Accommodation",
        allocated: 9000,
        spent: 6800,
        color: "bg-purple-500",
        icon: null,
      },
      {
        id: "food",
        name: "Food & Mahaprasad",
        allocated: 5500,
        spent: 3600,
        color: "bg-green-500",
        icon: null,
      },
      {
        id: "activities",
        name: "Tours & Activities",
        allocated: 3500,
        spent: 2800,
        color: "bg-orange-500",
        icon: null,
      },
    ],
  },
  "7": {
    totalBudget: 26000,
    tripName: "Somnath Temple Trip",
    dates: "October 2026",
    categories: [
      {
        id: "travel",
        name: "Travel & Transport",
        allocated: 9500,
        spent: 8050,
        color: "bg-blue-500",
        icon: null,
      },
      {
        id: "hotel",
        name: "Accommodation",
        allocated: 8500,
        spent: 6000,
        color: "bg-purple-500",
        icon: null,
      },
      {
        id: "food",
        name: "Food & Dining",
        allocated: 5000,
        spent: 2900,
        color: "bg-green-500",
        icon: null,
      },
      {
        id: "activities",
        name: "Gir Safari & Tours",
        allocated: 3000,
        spent: 2200,
        color: "bg-orange-500",
        icon: null,
      },
    ],
  },
  "8": {
    totalBudget: 48000,
    tripName: "Badrinath Temple Trip",
    dates: "June 2026",
    categories: [
      {
        id: "travel",
        name: "Travel & Transport",
        allocated: 18000,
        spent: 15300,
        color: "bg-blue-500",
        icon: null,
      },
      {
        id: "hotel",
        name: "Accommodation",
        allocated: 16000,
        spent: 13400,
        color: "bg-purple-500",
        icon: null,
      },
      {
        id: "food",
        name: "Food & Supplies",
        allocated: 9000,
        spent: 6000,
        color: "bg-green-500",
        icon: null,
      },
      {
        id: "activities",
        name: "Trek & Cable Car",
        allocated: 5000,
        spent: 3800,
        color: "bg-orange-500",
        icon: null,
      },
    ],
  },
  "9": {
    totalBudget: 22000,
    tripName: "Siddhivinayak Temple, Mumbai Trip",
    dates: "November 2026",
    categories: [
      {
        id: "travel",
        name: "Travel & Transport",
        allocated: 7000,
        spent: 5250,
        color: "bg-blue-500",
        icon: null,
      },
      {
        id: "hotel",
        name: "Accommodation",
        allocated: 7500,
        spent: 5500,
        color: "bg-purple-500",
        icon: null,
      },
      {
        id: "food",
        name: "Food & Dining",
        allocated: 4500,
        spent: 2100,
        color: "bg-green-500",
        icon: null,
      },
      {
        id: "activities",
        name: "Shopping & Tours",
        allocated: 3000,
        spent: 2250,
        color: "bg-orange-500",
        icon: null,
      },
    ],
  },
};
