import type { Place } from "@/packages/map/types";

// Trip-specific place data
export const TRIP_PLACES: Record<string, Place[]> = {
  // Golden Temple, Amritsar
  "1": [
    {
      id: "1",
      name: "Golden Temple",
      description: "Harmandir Sahib - Most sacred Sikh shrine",
      lat: 31.6200,
      lng: 74.8765,
      category: "attraction",
      time: "6:00 AM",
      address: "Golden Temple Road, Amritsar, Punjab, India",
    },
    {
      id: "2",
      name: "Jallianwala Bagh",
      description: "Historic memorial and public garden",
      lat: 31.6205,
      lng: 74.8795,
      category: "attraction",
      time: "10:00 AM",
      address: "Jallianwala Bagh, Amritsar, Punjab, India",
    },
    {
      id: "3",
      name: "Wagah Border",
      description: "India-Pakistan border ceremony location",
      lat: 31.6040,
      lng: 74.5722,
      category: "activity",
      time: "4:00 PM",
      address: "Wagah Border, Amritsar, Punjab, India",
    },
    {
      id: "4",
      name: "Partition Museum",
      description: "Museum dedicated to the partition of India",
      lat: 31.6340,
      lng: 74.8723,
      category: "attraction",
      time: "9:00 AM",
      address: "Town Hall, Amritsar, Punjab, India",
    },
  ],
  
  // Tirupati Balaji Temple
  "2": [
    {
      id: "1",
      name: "Tirupati Balaji Temple",
      description: "Lord Venkateswara Temple - World's richest temple",
      lat: 13.6833,
      lng: 79.3472,
      category: "attraction",
      time: "5:00 AM",
      address: "Tirumala, Tirupati, Andhra Pradesh, India",
    },
    {
      id: "2",
      name: "Sri Padmavathi Temple",
      description: "Temple dedicated to Goddess Padmavathi",
      lat: 13.6285,
      lng: 79.4192,
      category: "attraction",
      time: "8:00 AM",
      address: "Tiruchanur, Tirupati, Andhra Pradesh, India",
    },
    {
      id: "3",
      name: "Akasa Ganga Waterfall",
      description: "Sacred waterfall on Tirumala hills",
      lat: 13.6500,
      lng: 79.3400,
      category: "activity",
      time: "3:00 PM",
      address: "Tirumala Hills, Tirupati, Andhra Pradesh, India",
    },
    {
      id: "4",
      name: "Talakona Waterfall",
      description: "Highest waterfall in Andhra Pradesh",
      lat: 13.5741,
      lng: 79.5667,
      category: "activity",
      time: "11:00 AM",
      address: "Sri Venkateswara National Park, Andhra Pradesh, India",
    },
  ],
  
  // Vaishno Devi, Katra
  "3": [
    {
      id: "1",
      name: "Vaishno Devi Temple",
      description: "Holy cave temple dedicated to Goddess Vaishno Devi",
      lat: 33.0308,
      lng: 74.9495,
      category: "attraction",
      time: "4:00 AM",
      address: "Katra, Reasi, Jammu & Kashmir, India",
    },
    {
      id: "2",
      name: "Bhairavnath Temple",
      description: "Temple dedicated to Bhairav",
      lat: 33.0334,
      lng: 74.9521,
      category: "attraction",
      time: "7:00 AM",
      address: "Trikuta Hills, Jammu & Kashmir, India",
    },
    {
      id: "3",
      name: "Ardh Kuwari Cave",
      description: "Holy cave on the way to Vaishno Devi",
      lat: 33.0150,
      lng: 74.9350,
      category: "attraction",
      time: "10:00 AM",
      address: "Katra, Jammu & Kashmir, India",
    },
    {
      id: "4",
      name: "Banganga",
      description: "Sacred water source at the start of trek",
      lat: 33.0064,
      lng: 74.9311,
      category: "attraction",
      time: "5:00 AM",
      address: "Katra, Jammu & Kashmir, India",
    },
  ],
  
  // Kedarnath Temple
  "4": [
    {
      id: "1",
      name: "Kedarnath Temple",
      description: "Sacred Shiva temple in the Himalayas - Char Dham pilgrimage",
      lat: 30.7346,
      lng: 79.0669,
      category: "attraction",
      time: "6:00 AM",
      address: "Kedarnath, Rudraprayag, Uttarakhand, India",
    },
    {
      id: "2",
      name: "Gaurikund",
      description: "Starting point of Kedarnath trek",
      lat: 30.5911,
      lng: 79.0637,
      category: "activity",
      time: "5:00 AM",
      address: "Gaurikund, Uttarakhand, India",
    },
    {
      id: "3",
      name: "Vasuki Tal",
      description: "High-altitude glacial lake",
      lat: 30.7667,
      lng: 79.0500,
      category: "activity",
      time: "8:00 AM",
      address: "Near Kedarnath, Uttarakhand, India",
    },
    {
      id: "4",
      name: "Chorabari Tal (Gandhi Sarovar)",
      description: "Beautiful glacial lake near Kedarnath",
      lat: 30.7500,
      lng: 79.0833,
      category: "activity",
      time: "2:00 PM",
      address: "Kedarnath, Uttarakhand, India",
    },
  ],
  
  // Shri Mahakaleshwar Jyotirlinga Temple, Ujjain
  "5": [
    {
      id: "1",
      name: "Mahakaleshwar Jyotirlinga Temple",
      description: "Sacred Jyotirlinga temple dedicated to Lord Shiva",
      lat: 23.1828,
      lng: 75.7683,
      category: "attraction",
      time: "4:00 AM",
      address: "Ujjain, Madhya Pradesh, India",
    },
    {
      id: "2",
      name: "Ram Ghat",
      description: "Holy bathing ghat on Kshipra River",
      lat: 23.1771,
      lng: 75.7754,
      category: "attraction",
      time: "6:00 AM",
      address: "Ram Ghat Road, Ujjain, Madhya Pradesh, India",
    },
    {
      id: "3",
      name: "Kal Bhairav Temple",
      description: "Ancient temple dedicated to Kal Bhairav",
      lat: 23.1940,
      lng: 75.7849,
      category: "attraction",
      time: "10:00 AM",
      address: "Kal Bhairav Road, Ujjain, Madhya Pradesh, India",
    },
    {
      id: "4",
      name: "Harsiddhi Temple",
      description: "Shakti Peeth temple atop a hill",
      lat: 23.1790,
      lng: 75.7720,
      category: "attraction",
      time: "3:00 PM",
      address: "Harsiddhi Temple Road, Ujjain, Madhya Pradesh, India",
    },
  ],
  
  // Jagannath Temple, Puri
  "6": [
    {
      id: "1",
      name: "Jagannath Temple",
      description: "Sacred Hindu temple part of Char Dham pilgrimage",
      lat: 19.8048,
      lng: 85.8182,
      category: "attraction",
      time: "5:00 AM",
      address: "Grand Road, Puri, Odisha, India",
    },
    {
      id: "2",
      name: "Puri Beach",
      description: "One of the finest beaches on the east coast",
      lat: 19.8135,
      lng: 85.8312,
      category: "activity",
      time: "5:00 PM",
      address: "Beach Road, Puri, Odisha, India",
    },
    {
      id: "3",
      name: "Konark Sun Temple",
      description: "UNESCO World Heritage Site - 13th century temple",
      lat: 19.8876,
      lng: 86.0945,
      category: "attraction",
      time: "10:00 AM",
      address: "Konark, Odisha, India",
    },
    {
      id: "4",
      name: "Chilika Lake",
      description: "Largest coastal lagoon in India",
      lat: 19.7162,
      lng: 85.3206,
      category: "activity",
      time: "2:00 PM",
      address: "Chilika Lake, Odisha, India",
    },
  ],
  
  // Somnath Temple, Gujarat
  "7": [
    {
      id: "1",
      name: "Somnath Temple",
      description: "First among twelve Jyotirlinga shrines of Lord Shiva",
      lat: 20.8880,
      lng: 70.4013,
      category: "attraction",
      time: "6:00 AM",
      address: "Somnath, Prabhas Patan, Gujarat, India",
    },
    {
      id: "2",
      name: "Bhalka Tirtha",
      description: "Sacred spot where Lord Krishna left his mortal body",
      lat: 20.8900,
      lng: 70.3950,
      category: "attraction",
      time: "8:00 AM",
      address: "Veraval, Gujarat, India",
    },
    {
      id: "3",
      name: "Triveni Sangam",
      description: "Confluence of three holy rivers",
      lat: 20.8850,
      lng: 70.4100,
      category: "attraction",
      time: "10:00 AM",
      address: "Somnath, Gujarat, India",
    },
    {
      id: "4",
      name: "Somnath Beach",
      description: "Serene beach near the temple",
      lat: 20.8860,
      lng: 70.4030,
      category: "activity",
      time: "5:00 PM",
      address: "Somnath, Gujarat, India",
    },
  ],
  
  // Badrinath Temple, Uttarakhand
  "8": [
    {
      id: "1",
      name: "Badrinath Temple",
      description: "Sacred temple dedicated to Lord Vishnu - Char Dham pilgrimage",
      lat: 30.7433,
      lng: 79.4938,
      category: "attraction",
      time: "6:00 AM",
      address: "Badrinath, Chamoli, Uttarakhand, India",
    },
    {
      id: "2",
      name: "Mana Village",
      description: "Last Indian village before Tibet border",
      lat: 30.7500,
      lng: 79.5167,
      category: "attraction",
      time: "10:00 AM",
      address: "Mana, Uttarakhand, India",
    },
    {
      id: "3",
      name: "Vasudhara Falls",
      description: "Sacred 400-foot waterfall",
      lat: 30.7667,
      lng: 79.5333,
      category: "activity",
      time: "8:00 AM",
      address: "Near Mana Village, Uttarakhand, India",
    },
    {
      id: "4",
      name: "Tapt Kund",
      description: "Natural thermal springs near temple",
      lat: 30.7430,
      lng: 79.4935,
      category: "activity",
      time: "5:00 AM",
      address: "Badrinath, Uttarakhand, India",
    },
  ],
  
  // Siddhivinayak Temple, Mumbai
  "9": [
    {
      id: "1",
      name: "Siddhivinayak Temple",
      description: "Famous Ganesha temple in Mumbai",
      lat: 19.0176,
      lng: 72.8300,
      category: "attraction",
      time: "6:00 AM",
      address: "Prabhadevi, Mumbai, Maharashtra, India",
    },
    {
      id: "2",
      name: "Gateway of India",
      description: "Iconic monument overlooking Arabian Sea",
      lat: 18.9220,
      lng: 72.8347,
      category: "attraction",
      time: "10:00 AM",
      address: "Apollo Bunder, Mumbai, Maharashtra, India",
    },
    {
      id: "3",
      name: "Marine Drive",
      description: "Scenic promenade along the coast",
      lat: 18.9432,
      lng: 72.8236,
      category: "activity",
      time: "5:00 PM",
      address: "Marine Drive, Mumbai, Maharashtra, India",
    },
    {
      id: "4",
      name: "Haji Ali Dargah",
      description: "Mosque and tomb on an islet off the coast",
      lat: 18.9826,
      lng: 72.8089,
      category: "attraction",
      time: "3:00 PM",
      address: "Haji Ali, Mumbai, Maharashtra, India",
    },
  ],
};
